# Generated by Django 4.0.5 on 2022-07-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='department',
        ),
        migrations.AlterField(
            model_name='contratos',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContApp.vendors'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContApp.assets'),
        ),
    ]
