# Generated by Django 4.0.5 on 2022-07-21 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContApp', '0002_remove_contratos_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='donde',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ContApp.assets'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
